%% Pseudo-monopolar estimation demo
% This script:
% 1. Loads bipolar BrainSense Survey data and Lead-DBS coordinates
% 2. Consolidates repeated recordings
% 3. Computes pseudo-monopolar contact estimates
% 4. Plots:
%    - bipolar spectra
%    - bipolar pair matrix
%    - pseudo-monopolar bar plot
%    - GPe overlap vs pseudo-monopolar power

clear; clc;

% ------------------------------------------------------------------------
% Paths and input files
% -------------------------------------------------------------------------

scriptPath = pwd;
FOLDERPATH_DEMOS = fullfile(scriptPath, "demos");

bss_file = fullfile(FOLDERPATH_DEMOS, ...
    'sub-OP1002_ses-postop01_percept-bss_hemi-left.mat');

coord_file = fullfile(FOLDERPATH_DEMOS, ...
    'sub-OP1002_ses-postop01_lead-dbs-mni-coords_hemi-left.csv');

% ------------------------------------------------------------------------
% Load data
% -------------------------------------------------------------------------

tmp = load(bss_file);
selDataRaw = tmp.BipolarDB;

selDataCoords = readtable(coord_file);

% ------------------------------------------------------------------------
% Consolidate repeated recordings, if present
% -------------------------------------------------------------------------

cons_keys = [
    "patient_id", ...
    "session_id", ...
    "Hemisphere", ...
    "Sensing_ChannelbipP", ...
    "Sensing_ChannelbipN"
];

selData = consolidate_within_repetition(selDataRaw, cons_keys);

% ------------------------------------------------------------------------
% Select power metric
% -------------------------------------------------------------------------
% Options:
%   MeanPowerAlphaToT / MaxPowerAlphaToT       = total alpha power
%   MeanPowerAlpha    / MaxPowerAlpha          = relative alpha power
%   MeanPowerAlphaFlat / MaxPowerAlphaFlat     = periodic alpha power

power_metric = 'MaxPowerAlphaFlat';

% Name of pseudo-monopolar output variable generated by get_MONOPATTERN
power_metric_mono = [power_metric, 'Contr'];

% Choose correct frequency vector
if contains(power_metric, 'Flat')
    fvec = 'FrequencyFlat';
else
    fvec = 'Frequency';
end

% ------------------------------------------------------------------------
% Get patient and hemisphere labels
% -------------------------------------------------------------------------

if ismember('patient_id', selData.Properties.VariableNames)
    pid = string(selData.patient_id(1));
else
    pid = "unknown";
end

if ismember('Hemisphere', selData.Properties.VariableNames)
    hemi = string(selData.Hemisphere(1));
else
    hemi = "unknown";
end

% ------------------------------------------------------------------------
% Compute pseudo-monopolar estimate and join coordinates
% -------------------------------------------------------------------------

MonoPatternEst = get_MONOPATTERN(selData, power_metric);

MonoPatternData = join( ...
    MonoPatternEst, ...
    selDataCoords, ...
    "Keys", ["patient_id", "Hemisphere", "Sensing_Channel"] ...
);

% Ensure channel column is numeric
if ~isnumeric(MonoPatternData.Sensing_Channel)
    MonoPatternData.Sensing_Channel = double(string(MonoPatternData.Sensing_Channel));
end

% ------------------------------------------------------------------------
% Compute pair-level bipolar statistics
% -------------------------------------------------------------------------

pairs = unique( ...
    [selData.Sensing_ChannelbipP, selData.Sensing_ChannelbipN], ...
    'rows' ...
);

Gb_pairs = findgroups( ...
    selData.Sensing_ChannelbipP, ...
    selData.Sensing_ChannelbipN ...
);

Pstat = splitapply(@(x) x(1), selData.Sensing_ChannelbipP, Gb_pairs);
Nstat = splitapply(@(x) x(1), selData.Sensing_ChannelbipN, Gb_pairs);
Val   = splitapply(@mean, selData.(power_metric), Gb_pairs);

pairStats = table(Pstat, Nstat, Val, ...
    'VariableNames', {'P', 'N', 'Val'});

% Normalize values for color/size mapping
vmin = min(pairStats.Val, [], 'omitnan');
vmax = max(pairStats.Val, [], 'omitnan');
den  = max(vmax - vmin, eps);

pairStats.f = (pairStats.Val - vmin) ./ den;

% ---------------------------------------------------------------
% Define colors
% -------------------------------------------------------------------------

grey = [0.6 0.6 0.6];
blue = [0.1647 0.6745 0.8863];

mixcolor = @(f) grey .* (1 - f) + blue .* f;

pairColors = zeros(height(pairStats), 3);
for i = 1:height(pairStats)
    pairColors(i, :) = mixcolor(pairStats.f(i));
end

% ------------------------------------------------------------------------
% Create figure layout
% -------------------------------------------------------------------------

fig = figure( ...
    'Color', 'w', ...
    'Units', 'inches', ...
    'Position', [2 2 12 8] ...
);

tlo = tiledlayout(2, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

% ------------------------------------------------------------------------
% AX1: Bipolar spectra colored by pair-level alpha power
% -------------------------------------------------------------------------

ax1 = nexttile(1);
hold(ax1, 'on');

for k = 1:size(pairs, 1)

    pCh = pairs(k, 1);
    nCh = pairs(k, 2);

    % Select rows belonging to this bipolar pair
    C = selData( ...
        selData.Sensing_ChannelbipP == pCh & ...
        selData.Sensing_ChannelbipN == nCh, :);

    if isempty(C)
        continue;
    end

    % Get color from pairStats
    idxPS = find(pairStats.P == pCh & pairStats.N == nCh, 1, 'first');
    clr = pairColors(idxPS, :);

    % Aggregate possible duplicate rows by frequency
    Gf = findgroups(C.(fvec));
    fHz = splitapply(@(x) x(1), C.(fvec), Gf);

    if contains(power_metric, "Flat")
        psd = splitapply(@mean, C.MeanPowerFlat, Gf);
    elseif contains(power_metric, "Norm")
        psd = splitapply(@mean, C.MeanPowerNorm, Gf);
    else
        psd = splitapply(@mean, C.MeanPower, Gf);
    end

    plot(ax1, fHz, psd, ...
        'Color', clr, ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf('E%d-%d', pCh, nCh));
end

xlabel(ax1, "Frequency [Hz]");
ylabel(ax1, "PSD [uV^{2}/Hz]", 'Interpreter', 'tex');
title(ax1, sprintf('Grand-average bipolar survey: %s', power_metric));
legend(ax1, 'show', 'Location', 'northeastoutside');

xlim(ax1, [2 35]);
xticks(ax1, [4 8 12 30]);
set(ax1, 'XScale', 'log');

set(ax1, ...
    'FontName', 'Helvetica', ...
    'FontSize', 10, ...
    'TickDir', 'out', ...
    'LineWidth', 0.75, ...
    'Box', 'off');

grid(ax1, 'off');

% ------------------------------------------------------------------------
% AX2: Bipolar pair bubble matrix
% -------------------------------------------------------------------------

ax2 = nexttile(2);
hold(ax2, 'on');

contacts = 0:3;

P = pairStats.P;
N = pairStats.N;
V = pairStats.Val;
f = pairStats.f;

% Bubble size scales with normalized power
ms = 50 + 300 .* f;

% Draw light background grid
for c = contacts
    plot(ax2, ...
        [min(contacts)-0.5, max(contacts)+0.5], ...
        [c+0.5, c+0.5], ...
        '-', 'Color', [0.9 0.9 0.9], 'LineWidth', 0.5);

    plot(ax2, ...
        [c+0.5, c+0.5], ...
        [min(contacts)-0.5, max(contacts)+0.5], ...
        '-', 'Color', [0.9 0.9 0.9], 'LineWidth', 0.5);
end

% Bubble matrix
scatter(ax2, P, N, ms, V, ...
    'filled', ...
    'MarkerEdgeColor', [0.2 0.2 0.2], ...
    'LineWidth', 0.5);

% Custom grey-to-blue colormap
ncol = 256;
cmap = [
    linspace(grey(1), blue(1), ncol)', ...
    linspace(grey(2), blue(2), ncol)', ...
    linspace(grey(3), blue(3), ncol)'
];

colormap(ax2, cmap);
caxis(ax2, [vmin vmax]);

cb = colorbar(ax2);
cb.Label.String = power_metric;

xlim(ax2, [min(contacts)-0.5, max(contacts)+0.5]);
ylim(ax2, [min(contacts)-0.5, max(contacts)+0.5]);

set(ax2, 'XTick', contacts, 'YTick', contacts);
xlabel(ax2, 'Positive contact [+]');
ylabel(ax2, 'Negative contact [-]');
title(ax2, sprintf('%s — bipolar matrix', power_metric));

axis(ax2, 'ij');
axis(ax2, 'square');

set(ax2, ...
    'FontName', 'Helvetica', ...
    'FontSize', 10, ...
    'TickDir', 'out', ...
    'LineWidth', 0.75, ...
    'Box', 'off');

grid(ax2, 'off');

% ------------------------------------------------------------------------
% AX3: Pseudo-monopolar bar plot
% -------------------------------------------------------------------------

ax3 = nexttile(3);
hold(ax3, 'on');

channels = 0:3;
vals = nan(1, numel(channels));

for ii = 1:numel(channels)

    ch = channels(ii);

    Ci = MonoPatternData(MonoPatternData.Sensing_Channel == ch, :);

    if ~isempty(Ci)
        vals(ii) = mean(Ci.(power_metric_mono), 'omitnan');
    end
end

% Bar colors using viridis
[hexColours, ~] = map_values_to_cmap(vals, 'viridis');
rgbColours = hex2rgb(hexColours);

bh = bar(ax3, channels, vals, ...
    'FaceColor', 'flat', ...
    'EdgeColor', 'none');

bh.CData = rgbColours;

% Mark clinically selected/stimulated channels
if ismember('stimCHn', selData.Properties.VariableNames)

    stim_channels = unique(selData.stimCHn);
    stim_channels = stim_channels(~isnan(stim_channels));

    idx_stim = ismember(channels, stim_channels) & ~isnan(vals);

    x_stim = channels(idx_stim);
    y_stim = vals(idx_stim);

    y_offset = max(0.05 * range(vals, 'omitnan'), 0.01 * max(abs(vals), [], 'omitnan'));

    % Star
    plot(ax3, x_stim, y_stim + y_offset, '*', ...
        'Color', 'k', ...
        'MarkerSize', 10, ...
        'LineWidth', 1.5);

    % Text label
    for i = 1:numel(x_stim)
        text(ax3, x_stim(i), y_stim(i) + 2*y_offset, ...
            'channel selected', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'Color', 'k', ...
            'Rotation', 20);
    end
end

xticks(ax3, channels);
xlabel(ax3, 'Sensing channel');
ylabel(ax3, power_metric_mono);

title(ax3, sprintf( ...
    'Pseudo-monopolar estimation — Patient %s, %s', ...
    pid, hemi));

set(ax3, ...
    'FontName', 'Helvetica', ...
    'FontSize', 10, ...
    'TickDir', 'out', ...
    'LineWidth', 0.75, ...
    'Box', 'off');

grid(ax3, 'off');

% ------------------------------------------------------------------------
% AX4: GPe overlap vs pseudo-monopolar power
% -------------------------------------------------------------------------

ax4 = nexttile(4);
hold(ax4, 'on');

vals = nan(1, numel(channels));
gpe  = nan(1, numel(channels));

for ii = 1:numel(channels)

    ch = channels(ii);

    Ci = MonoPatternData(MonoPatternData.Sensing_Channel == ch, :);

    if ~isempty(Ci)

        vals(ii) = mean(Ci.(power_metric_mono), 'omitnan');

        if ismember('GPe', MonoPatternData.Properties.VariableNames)
            gpe(ii) = mean(Ci.GPe, 'omitnan');
        else
            warning('Column "GPe" not found in MonoPatternData.');
        end
    end
end

mask = ~isnan(vals) & ~isnan(gpe);

x = gpe(mask);
y = vals(mask);
plotColors = rgbColours(mask, :);

scatter(ax4, x, y, 70, plotColors, ...
    'filled', ...
    'MarkerEdgeColor', [0.2 0.2 0.2], ...
    'LineWidth', 0.75);

% Optional linear fit
if numel(x) >= 2

    p = polyfit(x, y, 1);

    xx = linspace(min(x), max(x), 100);
    yy = polyval(p, xx);

    plot(ax4, xx, yy, '-', ...
        'Color', [0.2 0.2 0.2], ...
        'LineWidth', 1);
end

xlabel(ax4, 'GPe overlap');
ylabel(ax4, power_metric_mono);

title(ax4, sprintf( ...
    'GPe vs %s — %s, %s', ...
    power_metric_mono, pid, hemi));

set(ax4, ...
    'FontName', 'Helvetica', ...
    'FontSize', 10, ...
    'TickDir', 'out', ...
    'LineWidth', 0.75, ...
    'Box', 'off');

grid(ax4, 'off');