% Grand-average bipolar survey with peak-aligned periodic alpha
clear; clc;

% Paths and data loading
scriptPath = pwd;
FOLDERPATH_DEMOS = fullfile(scriptPath, "demos");

data_file = fullfile( ...
    FOLDERPATH_DEMOS, ...
    'sub-OP1002_ses-postop01_percept-bss_hemi-left.mat');

tmp = load(data_file);
selDataRaw = tmp.BipolarDB;

% Consolidate repeated recordings
cons_keys = [
    "patient_id", ...
    "session_id", ...
    "Hemisphere", ...
    "Sensing_ChannelbipP", ...
    "Sensing_ChannelbipN"
];

selData = consolidate_within_repetition(selDataRaw, cons_keys);

% Labels
if ismember("patient_id", selData.Properties.VariableNames)
    pid = string(selData.patient_id(1));
else
    pid = "unknown";
end

if ismember("Hemisphere", selData.Properties.VariableNames)
    hemi = string(selData.Hemisphere(1));
else
    hemi = "unknown";
end

% Frequency bands and colors
bands = bml_get_canonical_bands([0, 150]);
bands.fmid = sqrt(bands.fstarts .* bands.fends);

newcolor = {'#d7191c', '#fdae61', '#fecc5c', '#abdda4', '#2b83ba'};
bands.color(2:6) = newcolor;

alphaColor = bands.color{3};

% Bootstraps param
nboots = 10000;


% Align periodic PSDs around individual alpha peaks
alignedFrequency = -32:0.5:32;

alignedPSDsAlphaPeak = nan(height(selData), numel(alignedFrequency));

for i = 1:height(selData)

    if ~ismember("FrequencyPeakAlpha", selData.Properties.VariableNames)
        continue;
    end

    if isnan(selData.FrequencyPeakAlpha(i))
        continue;
    end

    freq_shifted = selData.FrequencyFlat(i, :) - selData.FrequencyPeakAlpha(i);
    psd_flat = selData.MeanPowerFlat(i, :);

    alignedPSDsAlphaPeak(i, :) = interp1( ...
        freq_shifted, ...
        psd_flat, ...
        alignedFrequency, ...
        'linear', ...
        NaN);
end

selData.MeanPowerFlatAlphaAligned = alignedPSDsAlphaPeak;

% Bootstrap grand-average spectra

AvgPSD = mybootci(selData.MeanPower, nboots);
AvgPSDNorm = mybootci(selData.MeanPowerNorm, nboots);
AvgPSDFlat = mybootci(selData.MeanPowerFlat, nboots);

AvgPSDFlatAlphaShifted = mybootci( ...
    selData.MeanPowerFlatAlphaAligned, ...
    nboots);

% Figure: compact 2 x 2 panel layout
f2 = figure( ...
    "Color", "w", ...
    "Units", "pixels", ...
    "Position", [200 200 1100 850]);

t2 = tiledlayout(f2, 2, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

% Panel A: Absolute PSD
ax1 = nexttile(t2, 1);
hold(ax1, "on");

plotShaded( ...
    selData.Frequency(1, :) + eps, ...
    AvgPSD + eps, ...
    "k", ...
    "-", ...
    3);

xlim(ax1, [2 35]);
ylim(ax1, [0.01 8]);
xticks(ax1, [4 8 12 30]);

set(ax1, ...
    "XScale", "log", ...
    "YScale", "log", ...
    "FontName", "Helvetica", ...
    "FontSize", 10, ...
    "TickDir", "out", ...
    "LineWidth", 0.75, ...
    "Box", "off");

xlabel(ax1, "Frequency [Hz]");
ylabel(ax1, "PSD [absolute]");
title(ax1, "Absolute power");
grid(ax1, "off");

text(ax1, 0.02, 0.95, "A", ...
    "Units", "normalized", ...
    "FontWeight", "bold", ...
    "FontSize", 14);

% Panel B: Relative / normalized PSD
ax2 = nexttile(t2, 2);
hold(ax2, "on");

plotShaded( ...
    selData.Frequency(1, :) + eps, ...
    AvgPSDNorm + eps, ...
    alphaColor, ...
    "-", ...
    3);

xlim(ax2, [2 35]);
xticks(ax2, [4 8 12 30]);

set(ax2, ...
    "XScale", "log", ...
    "YScale", "log", ...
    "FontName", "Helvetica", ...
    "FontSize", 10, ...
    "TickDir", "out", ...
    "LineWidth", 0.75, ...
    "Box", "off");

xlabel(ax2, "Frequency [Hz]");
ylabel(ax2, "PSD [%]");
title(ax2, "Relative power");
grid(ax2, "off");

text(ax2, 0.02, 0.95, "B", ...
    "Units", "normalized", ...
    "FontWeight", "bold", ...
    "FontSize", 14);

% Panel C: Periodic / 1-f-corrected PSD
ax3 = nexttile(t2, 3);
hold(ax3, "on");

plotShaded( ...
    selData.FrequencyFlat(1, :) + eps, ...
    AvgPSDFlat + eps, ...
    alphaColor, ...
    "-", ...
    3);

xlim(ax3, [2 35]);
xticks(ax3, [4 8 12 30]);

set(ax3, ...
    "XScale", "log", ...
    "FontName", "Helvetica", ...
    "FontSize", 10, ...
    "TickDir", "out", ...
    "LineWidth", 0.75, ...
    "Box", "off");

xlabel(ax3, "Frequency [Hz]");
ylabel(ax3, "PSD [uV^{2}/Hz]", "Interpreter", "tex");
title(ax3, "Periodic power");
grid(ax3, "off");

text(ax3, 0.02, 0.95, "C", ...
    "Units", "normalized", ...
    "FontWeight", "bold", ...
    "FontSize", 14);

% Panel D: Peak-aligned periodic alpha PSD
ax4 = nexttile(t2, 4);
hold(ax4, "on");

plotShaded( ...
    alignedFrequency, ...
    AvgPSDFlatAlphaShifted, ...
    alphaColor, ...
    "-", ...
    3);

xlim(ax4, [-5 5]);
xticks(ax4, -5:1:5);
ylim(ax4, [0 0.7]);

set(ax4, ...
    "FontName", "Helvetica", ...
    "FontSize", 10, ...
    "TickDir", "out", ...
    "LineWidth", 0.75, ...
    "Box", "off");

xlabel(ax4, "Frequency relative to alpha peak [Hz]");
ylabel(ax4, "PSD [uV^{2}/Hz]", "Interpreter", "tex");
title(ax4, "Periodic alpha aligned to peak");
grid(ax4, "off");

text(ax4, 0.02, 0.95, "D", ...
    "Units", "normalized", ...
    "FontWeight", "bold", ...
    "FontSize", 14);

% Global title
title(t2, sprintf( ...
    "Grand-average bipolar survey — %s, %s", ...
    pid, hemi));